'use strict';
// Shareable detail routes use stable IDs rather than localized names.
const routeParams=new URLSearchParams(location.search);
const routeView=routeParams.get('view');
const routeProcedure=FLOW_LABELS[routeParams.get('procedure')]?routeParams.get('procedure'):'first';
const routeClinic=CLINICS.find(c=>c.id===routeParams.get('clinic'));
function selectedOffer(){const n=routeParams.get('offer');return n!==null&&/^\d+$/.test(n)?clinicOfferList(routeClinic)[Number(n)]||null:null;}
const flowPage=$('#flow-page');
const flowImages={hydration:'model-01-dewy.webp',texture:'model-01-dewy.webp',clarity:'model-10-dewy.webp',firmness:'model-10-dewy.webp',first:'clinic.webp'};
const flowHome=()=>location.pathname;
function flowHeading(step,title,backHref,backLabel){return `<a class="flow-back" href="${backHref}">← ${backLabel}</a><p class="eyebrow">${step}</p><h1 tabindex="-1" id="flow-title">${title}</h1>`;}
function routeCards(pid){return CLINICS.filter(c=>FLOW_OFFERINGS[c.id].includes(pid)).map(c=>clinicCard(c,pid)).join('');}
function procedurePage(){const p=PROCEDURES[routeProcedure];return `${flowHeading('01 / EXPLORE',p.title,flowHome()+'#discover','返回探索')}<div class="flow-intro"><img class="flow-cover" src="assets/${flowImages[routeProcedure]}" alt="示意圖片" width="1536" height="1024"><div><span class="flow-pill">先認識，再決定</span><p class="flow-lead">${p.intro}</p><p class="muted">圖片為氛圍示意；實際療程需經醫師評估。</p><a class="primary" href="#related-clinics">看看相關院所 ↓</a></div></div><div class="flow-facts"><div><h2>適合性</h2><p>由醫師依膚況與需求評估。</p></div><div><h2>恢復與行程</h2><p>請確認恢復期、注意事項與赴韓行程。</p></div><div><h2>費用與內容</h2><p>確認設備、範圍、次數及完整費用。</p></div></div><details class="flow-questions"><summary>諮詢時，可以這樣問</summary><ul>${p.questions.map(q=>`<li>${q}</li>`).join('')}</ul></details><section id="related-clinics" class="flow-related"><div class="section-heading"><div><p class="eyebrow">FIND YOUR PLACE</p><h2>相關院所</h2></div></div><p class="muted">實際院所與示例卡片分別標示，合作與預約安排仍需確認。</p><div class="clinic-grid">${routeCards(routeProcedure)}</div></section>`;}
function clinicPage(){const c=routeClinic,p=PROCEDURES[routeProcedure];if(!c||!FLOW_OFFERINGS[c.id].includes(routeProcedure))return missingPage();if(c.real)return realClinicPage(c);return `${flowHeading('02 / YOUR CLINIC',c.name,flowUrl('procedure',routeProcedure),'返回療程')}<p class="flow-location">SEOUL / ${c.area} · 最近車站與地址待確認</p><div class="flow-intro"><img class="flow-cover" src="assets/clinic.webp" alt="AI 生成院所示意圖" width="1536" height="1024"><div class="flow-offer"><span class="flow-pill">目前選擇</span><h2>${p.title}</h2><p class="flow-price">${flowPrice(c,routeProcedure)}</p><p class="muted">${routeProcedure==='hydration'?c.inclusions:'正式項目、設備、範圍與費用尚待院所確認。'}</p><a class="text-button" href="${flowUrl('procedure',routeProcedure)}">看看其他院所 ↗</a></div></div><p class="notice">以下為功能體驗用的虛構示例，非實際合作院所或醫療報價。</p><div class="flow-info-grid"><section><h2>溝通與費用</h2><dl><dt>中文服務</dt><dd>${c.language}</dd><dt>可能額外費用</dt><dd>${routeProcedure==='hydration'?c.extra:'正式諮詢時確認稅額、診察、麻醉與口譯費用。'}</dd></dl></section><section><h2>醫師、設備與產品</h2><p>正式上線前需取得並核實院所資料</p><p class="small muted">真實照片、醫師資料與資料確認日期尚待補充。</p></section><section><h2>預約與取消</h2><p>尚待實際院所條款確認</p><p>諮詢不等於預約完成；需由院所確認。</p></section><section><h2>回台後聯繫</h2><p>${c.followup}</p><button class="text-button" data-article="return">了解聯繫流程 ↗</button></section></div><div class="flow-reviews"><h2>真實心得</h2><p class="muted">尚無已核實的病患心得；不顯示虛構評分。</p></div><div class="flow-sticky"><button class="outline" data-save="${c.id}" aria-pressed="${saved.has(c.id)}">${saved.has(c.id)?'已收藏 ♥':'收藏院所 ♡'}</button><a class="primary" href="${flowUrl('consultation',routeProcedure,c.id)}">諮詢這個項目 ↗</a></div>`;}
function missingPage(){return `${flowHeading('SKINBRIDGE','找不到這個項目',flowHome()+'#clinics','返回探索')}<p>請重新選擇療程與院所。</p>`;}
function consultationPage(){const p=PROCEDURES[routeProcedure];if(!routeClinic)return `${flowHeading('03 / LET’S TALK','先選擇想諮詢的院所',flowHome()+'#clinics','返回探索')}<p class="muted">尚未決定療程也可以先了解。</p><div class="clinic-grid">${CLINICS.filter(c=>FLOW_OFFERINGS[c.id].includes(routeProcedure)).map(c=>`<a class="flow-picker" href="${flowUrl('consultation',routeProcedure,c.id)}"><strong>${c.name}</strong><span>${c.area} · ${p.title}</span><span>選擇院所 ↗</span></a>`).join('')}</div>`;if(!FLOW_OFFERINGS[routeClinic.id].includes(routeProcedure))return missingPage();const c=routeClinic;return `${flowHeading('03 / LET’S TALK','把問題帶進諮詢',flowUrl('clinic',routeProcedure,c.id),'返回院所')}<div class="consult-layout"><aside class="consult-selection"><p class="eyebrow">YOUR SELECTION</p><h2>${c.name}</h2><p>${c.area}</p><hr><h3>${p.title}</h3>${selectedOffer()?`<p class="notice">${esc(selectedOffer()[isKo?1:0])}<br>₩${selectedOffer()[2].toLocaleString('en-US')} · ${clinicOfferTerms(c)}</p>`:''}<p class="flow-price">${flowPrice(c,routeProcedure)}</p><a class="text-button" href="${flowUrl('procedure',routeProcedure)}">變更選擇 ↗</a><p class="small muted">資料狀態請見院所頁 · 預約前需確認</p></aside><form id="flow-consult-form"><fieldset class="date-choice"><legend>預計赴韓日期</legend><label><input type="radio" name="date-mode" value="unknown" checked>日期未定</label><label><input type="radio" name="date-mode" value="known">選擇日期</label></fieldset><label id="flow-date-label" hidden>預計赴韓日期<input type="date" id="flow-date" min="${today}" disabled></label><label>補充問題（選填）<textarea id="flow-question" rows="4" maxlength="600" placeholder="例如：中文服務、費用包含內容"></textarea></label><p class="small muted">請勿填寫病歷、照片或其他敏感資料。</p><button class="primary wide" type="submit">整理諮詢內容 ↗</button><p class="small muted">這裡只整理內容，不會自動傳送或完成預約。</p></form></div><section id="flow-summary-section" class="flow-summary" hidden><p class="eyebrow">READY WHEN YOU ARE</p><h2 tabindex="-1" id="summary-title">諮詢內容，整理好了。</h2><textarea id="flow-summary" class="summary-box" readonly aria-label="諮詢內容"></textarea><div class="dialog-actions"><button class="primary" id="flow-copy">複製諮詢內容</button>${/^https:\/\/(lin\.ee|line\.me)\//.test(LINE_URL)?`<a class="outline" href="${esc(LINE_URL)}" target="_blank" rel="noopener">開啟官方 LINE ↗</a>`:'<span class="flow-pill">LINE 連結準備中</span>'}</div><p class="muted">${LINE_URL?'複製後開啟 LINE，由妳確認並貼上傳送。':'目前 LINE 帳號尚未接入。沒有資料送出，也沒有成立預約。'}</p></section>`;}
if(['procedure','clinic','consultation'].includes(routeView)){
 document.body.classList.add('flow-mode');document.body.classList.toggle('clinic-mode',routeView==='clinic');
 [...$('#main').children].forEach(el=>el.hidden=el!==flowPage);flowPage.hidden=false;
 flowPage.innerHTML=routeView==='procedure'?procedurePage():routeView==='clinic'?clinicPage():consultationPage();
 document.title=$('#flow-title').textContent+' · skinbridge';
 // Home anchors must exit detail routes; only in-page related-clinics stays local.
 $$('a[href^="#"]').forEach(a=>{if(a.getAttribute('href')==='#plan'){a.href=flowUrl('consultation',routeProcedure,routeClinic?.id||'');}else if(!a.closest('#flow-page')&&!a.hasAttribute('data-open-saved')&&a.getAttribute('href')!=='#main')a.href=flowHome()+a.getAttribute('href');});
 $$('.review-language a').forEach(a=>a.href+=location.search);
 const form=$('#flow-consult-form');
 if(form){form.addEventListener('change',event=>{if(event.target.name==='date-mode'){const known=event.target.value==='known';$('#flow-date-label').hidden=!known;$('#flow-date').disabled=!known;$('#flow-date').required=known;}$('#flow-summary-section').hidden=true;});form.addEventListener('input',()=>$('#flow-summary-section').hidden=true);form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const date=$('#flow-date').disabled?'日期未定':$('#flow-date').value;const note=$('#flow-question').value.trim();$('#flow-summary').value=`【SKINBRIDGE 體驗版・未送出預約】\n想了解的院所：${routeClinic.name}（${routeClinic.area}）\n想了解的項目：${PROCEDURES[routeProcedure].title}\n費用參考：${flowPrice(routeClinic,routeProcedure)}\n${selectedOffer()?L('문의할 가격표 항목: ','想詢問的價格表項目：')+selectedOffer()[isKo?1:0]+' / ₩'+selectedOffer()[2].toLocaleString('en-US')+' / '+clinicOfferTerms(routeClinic)+'\n':''}預計赴韓日期：${date}\n${note?'補充問題：'+note+'\n':''}\n想確認：正式費用與包含項目、中文服務、取消條件、術後聯繫。\n以上為諮詢準備，非正式預約。`;$('#flow-summary-section').hidden=false;$('#summary-title').focus();});$('#flow-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#flow-summary').value);toast('已複製，可貼至諮詢對話');}catch{$('#flow-summary').focus();$('#flow-summary').select();toast('請複製已選取的諮詢內容');}});}
 document.addEventListener('click',event=>{const save=event.target.closest('[data-save]');if(save){$$('#flow-page [data-save]').forEach(button=>{const active=saved.has(button.dataset.save);button.setAttribute('aria-pressed',String(active));button.textContent=button.classList.contains('heart')?(active?'♥':'♡'):(active?'已收藏 ♥':'收藏院所 ♡');});} });
}
