'use strict';
// Shareable detail routes use stable IDs rather than localized names.
const routeParams=new URLSearchParams(location.search);
const routeView=routeParams.get('view');
const routeProcedure=FLOW_LABELS[routeParams.get('procedure')]?routeParams.get('procedure'):'first';
const routeClinic=CLINICS.find(c=>c.id===routeParams.get('clinic'));
function selectedOffer(){const n=routeParams.get('offer');return n!==null&&/^\d+$/.test(n)?clinicOfferList(routeClinic)[Number(n)]||null:null;}
const flowPage=$('#flow-page');
const flowImages={hydration:'care.webp',texture:'hero.webp',clarity:'serum.webp',firmness:'hero.webp',first:'clinic.webp'};
const flowHome=()=>location.pathname;
function flowHeading(step,title,backHref,backLabel){return `<a class="flow-back" href="${backHref}">← ${backLabel}</a><p class="eyebrow">${step}</p><h1 tabindex="-1" id="flow-title">${title}</h1>`;}
function routeCards(pid){return CLINICS.filter(c=>FLOW_OFFERINGS[c.id].includes(pid)).map(c=>clinicCard(c,pid)).join('');}
function procedurePage(){const p=PROCEDURES[routeProcedure];return `${flowHeading('01 / EXPLORE',p.title,flowHome()+'#discover','탐색으로 돌아가기')}<div class="flow-intro"><img class="flow-cover" src="../tw/assets/${flowImages[routeProcedure]}" alt="예시 이미지" width="1536" height="1024"><div><span class="flow-pill">먼저 알아보고 결정해요</span><p class="flow-lead">${p.intro}</p><p class="muted">사진은 분위기 예시이며 실제 시술은 의사 평가가 필요합니다.</p><a class="primary" href="#related-clinics">관련 병원 살펴보기 ↓</a></div></div><div class="flow-facts"><div><h2>나에게 맞는지</h2><p>피부 상태와 고민을 바탕으로 의사가 평가합니다.</p></div><div><h2>회복 기간과 여행 일정</h2><p>회복 기간과 주의사항을 확인하고 여행 일정을 계획하세요.</p></div><div><h2>비용과 포함 내용</h2><p>장비, 범위, 횟수와 전체 비용을 확인하세요.</p></div></div><details class="flow-questions"><summary>상담할 때 이렇게 물어보세요</summary><ul>${p.questions.map(q=>`<li>${q}</li>`).join('')}</ul></details><section id="related-clinics" class="flow-related"><div class="section-heading"><div><p class="eyebrow">FIND YOUR PLACE</p><h2>관련 병원</h2></div></div><p class="muted">실제 병원과 예시 카드를 구분해 표시했어요. 제휴와 예약 가능 여부는 확인이 필요합니다.</p><div class="clinic-grid">${routeCards(routeProcedure)}</div></section>`;}
function clinicPage(){const c=routeClinic,p=PROCEDURES[routeProcedure];if(!c||!FLOW_OFFERINGS[c.id].includes(routeProcedure))return missingPage();if(c.real)return realClinicPage(c);return `${flowHeading('02 / YOUR CLINIC',c.name,flowUrl('procedure',routeProcedure),'시술로 돌아가기')}<p class="flow-location">SEOUL / ${c.area} · 가까운 역·주소 확인 예정</p><div class="flow-intro"><img class="flow-cover" src="../tw/assets/clinic.webp" alt="AI 생성 병원 이미지" width="1536" height="1024"><div class="flow-offer"><span class="flow-pill">선택한 시술</span><h2>${p.title}</h2><p class="flow-price">${flowPrice(c,routeProcedure)}</p><p class="muted">${routeProcedure==='hydration'?c.inclusions:'실제 항목·장비·범위·비용은 병원 확인이 필요해요.'}</p><a class="text-button" href="${flowUrl('procedure',routeProcedure)}">다른 병원도 보기 ↗</a></div></div><p class="notice">기능 확인용 예시이며 실제 제휴 병원이나 견적이 아닙니다.</p><div class="flow-info-grid"><section><h2>언어 지원과 비용</h2><dl><dt>중국어 지원</dt><dd>${c.language}</dd><dt>추가 가능 비용</dt><dd>${routeProcedure==='hydration'?c.extra:'상담 시 세금·진료·마취·통역 비용을 확인하세요.'}</dd></dl></section><section><h2>의사·장비·제품</h2><p>정식 공개 전에 병원 자료를 확인할 예정</p><p class="small muted">실제 사진·의료진 정보·정보 확인일은 자료 확보 후 추가합니다.</p></section><section><h2>예약과 취소</h2><p>실제 병원 약관 확인 예정</p><p>상담만으로 예약이 완료되지 않으며 병원 확인이 필요합니다.</p></section><section><h2>귀국 후 연락</h2><p>${c.followup}</p><button class="text-button" data-article="return">연락 절차 알아보기 ↗</button></section></div><div class="flow-reviews"><h2>실제 후기</h2><p class="muted">확인된 실제 후기를 준비 중입니다. 가상의 평점은 표시하지 않아요.</p></div><div class="flow-sticky"><button class="outline" data-save="${c.id}" aria-pressed="${saved.has(c.id)}">${saved.has(c.id)?'찜 완료 ♥':'병원 찜하기 ♡'}</button><a class="primary" href="${flowUrl('consultation',routeProcedure,c.id)}">이 시술 상담하기 ↗</a></div>`;}
function missingPage(){return `${flowHeading('SKINBRIDGE','해당 항목을 찾을 수 없어요',flowHome()+'#clinics','탐색으로 돌아가기')}<p>시술과 병원을 다시 선택해 주세요.</p>`;}
function consultationPage(){const p=PROCEDURES[routeProcedure];if(!routeClinic)return `${flowHeading('03 / LET’S TALK','상담할 병원을 먼저 골라주세요',flowHome()+'#clinics','탐색으로 돌아가기')}<p class="muted">시술을 아직 정하지 못했어도 괜찮아요.</p><div class="clinic-grid">${CLINICS.filter(c=>FLOW_OFFERINGS[c.id].includes(routeProcedure)).map(c=>`<a class="flow-picker" href="${flowUrl('consultation',routeProcedure,c.id)}"><strong>${c.name}</strong><span>${c.area} · ${p.title}</span><span>병원 선택하기 ↗</span></a>`).join('')}</div>`;if(!FLOW_OFFERINGS[routeClinic.id].includes(routeProcedure))return missingPage();const c=routeClinic;return `${flowHeading('03 / LET’S TALK','궁금한 내용을 상담으로 이어가요',flowUrl('clinic',routeProcedure,c.id),'병원으로 돌아가기')}<div class="consult-layout"><aside class="consult-selection"><p class="eyebrow">YOUR SELECTION</p><h2>${c.name}</h2><p>${c.area}</p><hr><h3>${p.title}</h3>${selectedOffer()?`<p class="notice">${esc(selectedOffer()[isKo?1:0])}<br>₩${selectedOffer()[2].toLocaleString('en-US')} · ${clinicOfferTerms(c)}</p>`:''}<p class="flow-price">${flowPrice(c,routeProcedure)}</p><a class="text-button" href="${flowUrl('procedure',routeProcedure)}">선택 변경 ↗</a><p class="small muted">병원 상세에서 자료 출처 확인 · 예약 전 확인 필요</p></aside><form id="flow-consult-form"><fieldset class="date-choice"><legend>한국 방문 예정일</legend><label><input type="radio" name="date-mode" value="unknown" checked>아직 미정</label><label><input type="radio" name="date-mode" value="known">날짜 선택</label></fieldset><label id="flow-date-label" hidden>한국 방문 예정일<input type="date" id="flow-date" min="${today}" disabled></label><label>추가 질문 (선택)<textarea id="flow-question" rows="4" maxlength="600" placeholder="예: 중국어 지원이나 가격 포함 항목이 궁금해요"></textarea></label><p class="small muted">병력·사진 등 민감한 정보는 입력하지 마세요.</p><button class="primary wide" type="submit">상담 내용 정리하기 ↗</button><p class="small muted">내용만 정리하며 자동 전송되거나 예약되지 않아요.</p></form></div><section id="flow-summary-section" class="flow-summary" hidden><p class="eyebrow">READY WHEN YOU ARE</p><h2 tabindex="-1" id="summary-title">상담 내용을 정리했어요</h2><textarea id="flow-summary" class="summary-box" readonly aria-label="상담 내용"></textarea><div class="dialog-actions"><button class="primary" id="flow-copy">상담 내용 복사</button>${/^https:\/\/(lin\.ee|line\.me)\//.test(LINE_URL)?`<a class="outline" href="${esc(LINE_URL)}" target="_blank" rel="noopener">공식 LINE 열기 ↗</a>`:'<span class="flow-pill">LINE 연결 준비 중</span>'}</div><p class="muted">${LINE_URL?'복사한 뒤 LINE을 열고, 내용을 확인해 직접 붙여넣어 보내세요.':'아직 LINE 계정이 연결되지 않았어요. 전송되거나 예약된 내역은 없습니다.'}</p></section>`;}
if(['procedure','clinic','consultation'].includes(routeView)){
 document.body.classList.add('flow-mode');document.body.classList.toggle('clinic-mode',routeView==='clinic');
 [...$('#main').children].forEach(el=>el.hidden=el!==flowPage);flowPage.hidden=false;
 flowPage.innerHTML=routeView==='procedure'?procedurePage():routeView==='clinic'?clinicPage():consultationPage();
 document.title=$('#flow-title').textContent+' · skinbridge';
 // Home anchors must exit detail routes; only in-page related-clinics stays local.
 $$('a[href^="#"]').forEach(a=>{if(a.getAttribute('href')==='#plan'){a.href=flowUrl('consultation',routeProcedure,routeClinic?.id||'');}else if(!a.closest('#flow-page')&&!a.hasAttribute('data-open-saved')&&a.getAttribute('href')!=='#main')a.href=flowHome()+a.getAttribute('href');});
 $$('.review-language a').forEach(a=>a.href+=location.search);
 const form=$('#flow-consult-form');
 if(form){form.addEventListener('change',event=>{if(event.target.name==='date-mode'){const known=event.target.value==='known';$('#flow-date-label').hidden=!known;$('#flow-date').disabled=!known;$('#flow-date').required=known;}$('#flow-summary-section').hidden=true;});form.addEventListener('input',()=>$('#flow-summary-section').hidden=true);form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const date=$('#flow-date').disabled?'아직 미정':$('#flow-date').value;const note=$('#flow-question').value.trim();$('#flow-summary').value=`【SKINBRIDGE 검토판 · 예약 미전송】\n문의할 병원: ${routeClinic.name}（${routeClinic.area}）\n궁금한 시술：${PROCEDURES[routeProcedure].title}\n비용 참고: ${flowPrice(routeClinic,routeProcedure)}\n${selectedOffer()?L('문의할 가격표 항목: ','想詢問的價格表項目：')+selectedOffer()[isKo?1:0]+' / ₩'+selectedOffer()[2].toLocaleString('en-US')+' / '+clinicOfferTerms(routeClinic)+'\n':''}한국 방문 예정일：${date}\n${note?'추가 질문：'+note+'\n':''}\n확인할 내용: 실제 비용과 포함 항목, 중국어 지원, 취소 조건, 사후관리 연락.\n상담 준비용이며 실제 예약이 아닙니다.`;$('#flow-summary-section').hidden=false;$('#summary-title').focus();});$('#flow-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#flow-summary').value);toast('복사했어요. 상담 대화에 붙여넣을 수 있어요');}catch{$('#flow-summary').focus();$('#flow-summary').select();toast('선택된 상담 내용을 복사해 주세요');}});}
 document.addEventListener('click',event=>{const save=event.target.closest('[data-save]');if(save){$$('#flow-page [data-save]').forEach(button=>{const active=saved.has(button.dataset.save);button.setAttribute('aria-pressed',String(active));button.textContent=button.classList.contains('heart')?(active?'♥':'♡'):(active?'찜 완료 ♥':'병원 찜하기 ♡');});} });
}
