'use strict';
// Source-backed clinic profiles. Editorial inclusion does not imply partnership.
const isKo=document.documentElement.lang==='ko';
const L=(ko,tw)=>isKo?ko:tw;
const REAL_CLINICS=[
 {id:'selena',real:true,name:L('셀레나의원 홍대','SELENA Clinic 弘大'),area:L('홍대','弘大'),concerns:[L('잡티','斑點'),L('탄력','緊緻'),L('모공','毛孔')],price:null,language:L('중국어 서비스 소개 · 방문일 지원 확인','資料介紹中文服務 · 到訪日需確認'),extra:L('행사표는 부가세 별도 · 그 외 비용 확인','活動表未含 VAT · 其他費用需確認'),followup:L('귀국 후 연락 창구·응답 시간 확인 필요','返台後聯絡窗口與回覆時間待確認'),brand:'SELENA',source:'https://selenaskin.com/',address:L('서울 마포구 양화로 162, 좋은사람들빌딩 9층','首爾麻浦區楊花路 162，9 樓'),station:L('홍대입구역 8번 출구 앞','弘大入口站 8 號出口前'),intro:L('홍대 일정에 맞춰, 시술과 비용부터 차근차근.','配合弘大行程，先了解項目與費用。'),sections:[
 [L('방문 시간','看診時間'),L('평일 10:00–20:00 (접수 마감 19:00). 토·일·공휴일 10:00–18:00 (접수 마감 17:00). 점심시간 없이 운영하며 설날·추석 당일 휴진합니다.','平日 10:00–20:00（最後受理 19:00）；週末及國定假日 10:00–18:00（最後受理 17:00）。無午休；春節、中秋節當日休診。')],
 [L('의료진과 시술','醫師與項目'),L('공식 홈페이지 대표자: 이상경. 제공된 소개서와 홈페이지에서 피코토닝, 리프팅, 필러·스킨부스터 등을 안내합니다. 담당 의료진과 사용할 장비·제품은 상담 시 확인하세요.','官網代表：이상경。提供的介紹書及官網介紹皮秒、拉提、填充與肌膚注射等項目。實際醫師、設備及產品請於諮詢時確認。')],
 [L('언어와 예약','語言與預約'),L('소개서는 한국어·중국어·일본어·영어·태국어 서비스를 안내합니다. 방문일 통역 가능 여부와 비용, 예약 변경·취소 조건은 별도 확인이 필요합니다.','介紹書列出韓文、中文、日文、英文及泰文服務。到訪日的口譯安排、費用與更改取消條件需另行確認。')],
 [L('귀국 후 문의','返台後聯繫'),L('제공된 자료에는 사후관리 연락 창구와 응답 시간이 없습니다. 예약 전에 확인할 항목으로 남겨두었습니다.','提供的資料未列出術後聯絡窗口與回覆時間，請於預約前確認。')]
 ]},
 {id:'springday-sinchon',real:true,name:L('다시봄날의원 신촌점','Springday Clinic 新村'),area:L('신촌','新村'),concerns:[],price:null,language:L('중·영·일 지원은 방문일에 따라 확인','中英日語支援依到訪日確認'),extra:L('시술·세금·통역 포함 비용 확인','療程、稅額與口譯費用需確認'),followup:'springdayclinic3@naver.com',brand:'SPRINGDAY',source:'https://sch.springdayclinic.com/for-foreigners-guide-springdayclinic-sinchon?lang=zh-tw',address:L('서울 서대문구 신촌로 99, 7층·9층','首爾西大門區新村路 99，7 樓及 9 樓'),station:L('신촌역 3번 출구 약 16m · 첫 접수는 7층','新村站 3 號出口約 16 公尺 · 先至 7 樓報到'),intro:L('신촌에서 상담하고, 귀국 후 연락 방법까지 확인하세요.','在新村諮詢，也先確認返台後的聯繫方式。'),sections:[
 [L('방문 시간과 동선','時間與交通'),L('평일 10:00–20:00, 점심 14:00–15:00. 토요일 10:00–16:00, 별도 점심시간 없음. 일요일 휴진, 공휴일 별도 공지. 지하철 지하 통로에서 건물 지하 1층으로 연결됩니다.','平日 10:00–20:00，午休 14:00–15:00；週六 10:00–16:00，無另設午休。週日休診，假日依公告。地鐵地下通道可連接大樓 B1。')],
 [L('의료진과 상담','醫師與諮詢'),L('공식 소개의 대표원장은 이보원입니다. 희망하는 필러·콜라겐 관련 시술과 담당 의료진은 예약 전 문의하세요. 모든 시술을 대표원장이 직접 진행한다고 확정하지 않습니다.','官方介紹的代表院長為 Bo Won Lee。填充及膠原相關項目與實際負責醫師請於預約前確認；未承諾所有項目皆由代表院長施作。')],
 [L('언어 지원','語言支援'),L('중국어·영어·일본어 지원은 직원과 방문일에 따라 달라집니다. 현장 통역이 항상 제공되는 것은 아니며 번역 도구를 사용할 수 있습니다.','中文、英文、日文支援依人員及日期而異；未保證隨時有現場口譯，可能使用翻譯工具。')],
 [L('귀국 후 문의','返台後聯繫'),L('공식 외국인 안내는 사전 상담과 귀국 후 문의 이메일 springdayclinic3@naver.com을 안내합니다. 응답 시간은 명시되어 있지 않으며 현지 대면 진료가 필요할 수 있습니다.','官方外國人指南列出事前及返國後聯絡信箱 springdayclinic3@naver.com。未列回覆時限，必要時仍需在當地面診。')]
 ]}
];
// Two supplied artwork variants contain the same 22 rows; year is not printed.
const SELENA_OFFERS=[
 ['皮秒淨膚雷射','피코토닝',57000],['皮秒淨膚雷射 + 維他命美白管理','피코토닝 + 비타민 관리',96000],['麗珠蘭黑盒 2cc + 軟膜','리쥬란 블랙 2cc + 모델링팩',193000],['喬雅露藍盒 2cc','쥬베룩 블루 2cc',98000],['喬雅露黑盒 2cc','쥬베룩 블랙 2cc',156000],['黃金微針 + 軟膜 1次','황금 미세침 + 모델링팩 1회',129000],['黃金微針 全臉 + 軟膜 5次','황금 미세침 얼굴 전체 + 모델링팩 5회',449000],['InMode FX模式 4分鐘 + 海芙音波 300發','인모드 FX 4분 + 슈링크 300샷',171000],['海芙音波 300發 + 全臉提升肉毒(CORETOX) + 軟膜','슈링크 300샷 + 얼굴 전체 리프팅 보톡스(CORETOX) + 모델링팩',179000],['海芙電波 300發 + LDM 12分鐘','볼뉴머 300샷 + LDM 12분',348000],['海芙電波 600發 + LDM 12分鐘','볼뉴머 600샷 + LDM 12분',552000],['海芙音波 600發 + 海芙電波 600發 + LDM 12分鐘','슈링크 600샷 + 볼뉴머 600샷 + LDM 12분',727000],['美版音波 300發 + 鳳凰電波 600發','울쎄라 300샷 + 써마지 600샷',2793000],['美版音波 600發 + 鳳凰電波 600發','울쎄라 600샷 + 써마지 600샷',3724000],['Onda 70kj + 鈦提升 40kj','온다 70kJ + 티타늄 40kJ',1106000],['Onda 70kj + 美版音波 300發','온다 70kJ + 울쎄라 300샷',1494000],['身體Onda 100kj + 身體輪廓針 10cc','바디 온다 100kJ + 바디 윤곽주사 10cc',630000],['身體Onda 200kj + 身體輪廓針 20cc','바디 온다 200kJ + 바디 윤곽주사 20cc',1261000],['白玉針 5+1 (5次 + 贈送1次)','백옥주사 5+1 (5회 + 1회 증정)',200000],['白玉針 10+2 (10次 + 贈送2次)','백옥주사 10+2 (10회 + 2회 증정)',300000],['鮭魚針 1cc','연어주사 1cc',20000],['Lilied-M 1cc','릴리이드-M 1cc',20000]
];
function realClinicMedia(c){return `<div class="clinic-placeholder"><span>SEOUL / ${c.area}</span><strong>${c.brand}</strong><span>${L('병원 사진 준비 중','院所照片準備中')}</span></div>`;}
function realClinicPage(c){const offerRows=SELENA_OFFERS.map((o,i)=>`<div class="offer-row"><div><strong>${esc(o[isKo?1:0])}</strong>${isKo?`<small>${esc(o[0])}</small>`:''}</div><span>₩${o[2].toLocaleString('en-US')}<small>${L('부가세 별도','未含 VAT')}</small></span><a class="text-button" href="${flowUrl('consultation',routeProcedure,c.id)}&offer=${i}">${L('문의','詢問')} ↗</a></div>`).join('');return `${flowHeading('02 / YOUR CLINIC',c.name,flowHome()+'#clinics',L('병원 목록','院所列表'))}<p class="flow-location">${c.station}</p><div class="flow-intro">${realClinicMedia(c)}<div><span class="flow-pill">${L('실제 병원 자료','實際院所資料')}</span><p class="flow-lead">${c.intro}</p><p>${c.address}</p><p class="muted">${c.language}</p><a class="text-button" href="${c.source}" target="_blank" rel="noopener">${c.id==='tunes'?L('공공기관 등록 안내','公共機構登錄資訊'):L('병원 공식 안내','院所官方資訊')} ↗</a></div></div><p class="small muted">${L('2026.10.04 자료 정리 · 제휴·예약 연결은 아직 확정되지 않았습니다.','資料整理：2026.10.04 · 尚未確認合作與預約串接。')}</p>${c.id==='tunes'?tunesPriceSection():''}${c.id==='selena'?`<section class="real-offers"><p class="eyebrow">A LITTLE EXTRA</p><h2>${L('궁금한 시술, 제공받은 행사표에서 확인해요','從提供的活動表，了解感興趣的項目')}</h2><p class="notice">${L('자료 표기: 10/1–10/31 · 연도 미표기 · 전 항목 부가세 별도. 현재 적용 여부·장비 모델·추가 비용은 병원 확인이 필요합니다. 한국어 시술명은 검토용 번역이며 원문을 함께 표시합니다.','原稿：10/1–10/31，未標年份；全項目未含 VAT。適用日期、設備型號及額外費用須向院所確認。')}</p>${offerRows.split('<div class="offer-row">').slice(0,4).join('<div class="offer-row">')}<details><summary>${L('전체 22개 항목 보기','查看全部 22 個項目')}</summary>${SELENA_OFFERS.slice(3).map((o,j)=>`<div class="offer-row"><div><strong>${esc(o[isKo?1:0])}</strong>${isKo?`<small>${esc(o[0])}</small>`:''}</div><span>₩${o[2].toLocaleString('en-US')}<small>${L('부가세 별도','未含 VAT')}</small></span><a class="text-button" href="${flowUrl('consultation',routeProcedure,c.id)}&offer=${j+3}">${L('문의','詢問')} ↗</a></div>`).join('')}</details></section>`:''}<div class="flow-info-grid">${c.sections.map(s=>`<section><h2>${s[0]}</h2><p>${s[1]}</p></section>`).join('')}</div><p class="small muted">${L('출처: 병원 공식 안내 및 제공 자료. 시술 적합성은 의료진 상담이 필요합니다.','來源：院所官方資訊與提供資料。療程適合性需經醫師評估。')}</p><div class="flow-sticky"><button class="outline" data-save="${c.id}" aria-pressed="${saved.has(c.id)}">${saved.has(c.id)?L('찜했어요 ♥','已收藏 ♥'):L('병원 찜하기 ♡','收藏院所 ♡')}</button><a class="primary" href="${flowUrl('consultation',routeProcedure,c.id)}">${L('상담 내용 준비하기','整理諮詢內容')} ↗</a></div>`;}
